# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 03 May 2018 22:18:50 +0000
*	@ALL	0
*	@user	1
*	@vertigo	16
files	@user	0
files	@vertigo	2
