<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: hongdemian
 * Date: Wed, 09 May 2018 16:19:29 -0600
 */

$conf['title'] = 'Vertigo -  Solutions For Work At Height, Health & Safety Management System';
$conf['start'] = 'home2';
$conf['sidebar'] = 'toc';
$conf['license'] = '0';
$conf['recent_days'] = 30;
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username_link';
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['plugin']['googleanalytics']['GAID'] = 'UA-114902721-3';
$conf['plugin']['googleanalytics']['track_users'] = 1;
$conf['plugin']['googleanalytics']['track_links'] = 1;

// end auto-generated content
