<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Thu, 03 May 2018 22:18:50 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
